services:
  db:
    image: postgres:16.3
    container_name: my-postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    container_name: my-spring-boot-app
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: ./frontend
    container_name: my-nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
volumes:
  postgres-data:
